### ISSUE TITLE
Data vs [UInt8]?

### ISSUE THREAD

**Issue by travisgriggs** [PasiSalenius/LightMQTT#12]
I'm curious if you've looked at using `Data` structs instead of `[UInt8]` arrays. Initially, I thought there was quite a bit of the arrays, but on further reflection, it seems that it's mostly in building up packet headers. When I switch to Swift3, I begin using Data in all the places I had been using [UInt8]. I'd be willing to work up a PR if there's interest in that.

**Comment by PasiSalenius** [comment]
One of the reasons I built my own MQTT client was to make it as plain Swift, bare bones, value-data-typed as possible. So not knowing the full innards of Data, I wanted to have a good view under the hood, in case some bottlenecks would surface at high MQTT message loads. So that's why I liked example codes I found with UInt8, and I think [UInt8] is the most plain view to the data as I can get.

Now, I could be wrong, and perhaps Data does some low level optimizations that aren't possible with UInt8 arrays, but I really appreciate the simple way things currently look.

If you want to try this out, by reimplementing UInt8 arrays as Data, please then test it out with high messages throughput (100s of msgs / sec or more). I'd be interested to hear how it turned out.

In my use case it's what comes after reading to UnsafeMutablePointer<UInt8> from InputStream that easily becomes the bottle neck (in addition to the eventual JSON parsing). As the UnsafeMutablePointer is UInt8, I visually like the header bytes to also be built using UInt8.

I don't know if this made any sense, but that's my 2 cents :-)

**Comment by travisgriggs** [comment]
I had a go at this today. My first attempt failed. I think we're looking at different places. I don't think Data would help or hurt on the inputStream side. Data doesn't do anything really to make streaming easier (but writing a DataStream class *does* <<grin>>).

My experience was more on the "building up side", mostly because Data is easier to add extensions too than Array<UInt8>. And Swift libraries seem to use them more. I *did* write a version that did this. Unfortunately the extensions clash with extensions I'm using in my own code base. I think I have a better idea now how to simplify the "building up" of the control packets. So I'll have one more go at that and then report back (and close the issue one way or the other at that point).

**Comment by travisgriggs** [comment]
#15 has been submitted
