### ISSUE TITLE
connect() blocks

### ISSUE THREAD

**Issue by travisgriggs** [PasiSalenius/LightMQTT#14]
I ran into an interesting problem today. The read function of the LightMQTT runs async on a DispatchQueue of programmer choosing, the the actual connect does. I had an app that was trying to connect to a broker from within a pretty restricted network. It eventually timeout, but had the UI blocked until then.

I'm not a GCD expert at all. What would be correct way to deal with this? Just wrap the `connect` in a similar `async` wrapper as the one it will hand off to the read loop? Or should LightMQTT be doing that itself?

**Comment by PasiSalenius** [comment]
That seems to be right. I thought I already managed to fix blocking but it's easy to see it still blocks, if I enable Network Link Conditioner in iOS developer options.

It must currently block here, while waiting for TCP socket to open
```
while input.streamStatus == .opening || output.streamStatus == .opening {
    usleep(1000)
}
```

The code needs some changes for it to handle connecting asynchronously.

Best approach would probably be to have a completion block on the public connect() method, that returns a success flag (and possible network error). This way the user could subscribe to topics right after connect has completed. The block could be carried from connect() to mqttConnect().

Completion blocks for subscribe/unsubscribe/publish would also be nice, but implementing them is pretty difficult, since ACKs are received on a different thread altogether. I think they could return a success flag, and fail when streams are nil or not open. Any real asynchoronous completion block would require too much work IMO.

**Comment by PasiSalenius** [comment]
I committed an implementation for async connect() method with an optional completion block. I tested it somewhat and it seems to get rid of the main thread blocking with link conditioner set to bad network.

**Comment by travisgriggs** [comment]
I'll test it in a little bit, hopefully today.

**Comment by travisgriggs** [comment]
> Completion blocks for subscribe/unsubscribe/publish would also be nice, but implementing them is pretty difficult, since ACKs are received on a different thread altogether. I think they could return a success flag, and fail when streams are nil or not open. Any real asynchoronous completion block would require too much work IMO.

I think these are more or less OK, because the flow of commands and responses is basically serialized by the tcp/ip stream.

**Comment by travisgriggs** [comment]
Tested and works fine. Nice fix.
