### ISSUE TITLE
No API for username/password

### ISSUE THREAD

**Issue by travisgriggs** [PasiSalenius/LightMQTT#4]
There is currently no API for setting the username/password used at connect time. I'll submit a PR for this soon.

It leads to an interesting question stylistically that I would like some feedback on. As more and more options are added that affect the behavior of connect is it preferable to 

A) add more options (with default arguments?) to the connect() parameter list?
B) just move them to `var`s of the class and the API is that you set them before calling an argumentless connect()?
C) be "swifty" and make the arguments an enum so you get type safety on them? e.g.

    class LightMQTT {
        ...
        enum ConnectionOption {
            case username(String)
            case password(String)
            case useTLS(Bool)
        }
        ...
        func connect(options:[ConnectionOption] = []) {
            ...
        }
        ...
    }

usage:

    let client = LightMQTT()
    client.connect([.useTLS(true), .username("foo"), .password("bar")])

I'm ambivalent myself at this point...

**Comment by PasiSalenius** [comment]
I checked how other similar Swift MQTT libraries did this:
- In https://github.com/emqtt/CocoaMQTT you set these as properties on the client instance
- In https://github.com/aciidb0mb3r/SwiftMQTT they seem to be set as initialization arguments

I'm actually planning to work on fixing some longstanding issues when the same client is disconnected and reconnected repeatedly (exactly what happens in my iOS app). I want to keep the same LightMQTT client instance around. But it should not get confused of which input/output streams to use.

Also, now the optional self is used for checks where it does not make sense, since currently the streams might have been reconnected, and even the hostname may have been changed.

I'm thinking of
- making some connection parameters like hostname and port private, only set at initialization time
- capturing a reference to the outputStream along with inputStream, to make sure the pair is used together for the duration of that stream lifetime

**Comment by PasiSalenius** [comment]
Okay got all of my changes done now.

I think you should implement this by adding more parameters to the client initializer, with default values. The current style seems pretty neat, at least up until the point where there are 20 different properties to define values for :)

Now, what would be a nice way to prevent those eventual public properties (like useTLS) being modified while the client is connected? Or should they only apply as the client is reconnected? I would want to keep clients reusable...

**Comment by PasiSalenius** [comment]
And now that I take look at your ConnectionOption idea again, I really think that's the way to go.

Could we make it ClientOption instead and give it as optional argument for initializer? Otherwise it is possible to disconnect and reconnect with different options, in which case any remaining background threads would get these options changed from under them. It would seem logical for them to be static for the lifetime of one client instance.

You're welcome to do this change if you want.

**Comment by travisgriggs** [comment]
With your latest changes, the pattern so far seems to be `private var` properties (which will keep any client from messing with them from connect to connect), default values where appropriate (I think it *may* be redundant to both have default initializer arguments and default declaration initializers), and all values set through the initializer (some defaulted). For now, I'll follow that pattern for the username/password combo. If I attempt a refactoring, I'll submit those in a strict refactoring (no new options).

**Comment by PasiSalenius** [comment]
I guess this can be considered closed now.
